# Generated by Django 5.0.1 on 2024-01-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('sale', models.BooleanField(default=False)),
                ('sale_percent', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
